markdown: rdiscount
pygments: true
safe: true
source: ./
destination: ./_site
lsi: false


# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#          
analytics :
  provider : google
  google : 
      tracking_id : 'UA-123-12'
  getclicky :
    site_id :
